from transformers import AutoTokenizer
from auto_compressor import AutoCompressorModel
import pdb

# Load a model pre-trained on 6k tokens in 4 compression steps
tokenizer = AutoTokenizer.from_pretrained("princeton-nlp/AutoCompressor-2.7b-6k")

# pdb.set_trace()
rc_1 = '''
User: Passage: "Neighborhood Legal Services, which provides free legal services to the poor, has expanded into the San Gabriel and Pomona valleys, areas with large Asian populations, many of whom speak limited or no English. Language is their biggest obstacle, but the Asian communities' cultural isolation and service providers' lack of cultural expertise also play a part, said NLS executive director Neal Dubovitz. And with 13 percent to 15 percent of the Asian population in the U.S. living below the poverty line, NLS services are badly needed, Dubovitz said. "Although it is a significant part of the poverty population, Asians historically have not been able to participate in the services and programs available to the poor," he said. From simple telephone advice to complete legal representation in court, the agency provides free consumer, health, family, immigration, housing, public benefits and labor legal services to people who earn under $1,380 per month. Legal service providers have long served large Latino populations, who have cultural diversity but share a common language. "I remember the days when there were only a handful of people in the legal offices who spoke Spanish," Dudovitz said. "Now Spanish and English are interchangeable. Our goal is to have that for the major Asian languages as well." Before the expansion, only a few NLS lawyers spoke Asian languages, said attorney Rebecca Yee, who was hired by NLS in April 2002 to design and head the project. "Now we have people speaking Cantonese, Mandarin, Thai, Khmer (from Cambodia), Korean, Vietnamese, Japanese and Tagalog," Yee said. One of the 13 attorneys hired to work with the program is Irene Mak, a family law attorney who speaks Cantonese, Mandarin and Thai. Mak was a partner at a private law firm before she went to work for NLS two years ago, earning up to $20,000 less a year working on domestic violence cases. "The job is more satisfying than the money," said Mak, who grew up in Hong Kong and Thailand before coming to the United States. "I could use my language skills and wanted to give back to the Asian community." NLS expanded when Legal Services Corp., the federal agency that funds providers of free legal services nationwide, reduced the number of grantees in the Los Angeles area from five to three, Dudovitz said. NLS won the competitive grant over the Legal Services Program for Pasadena, San Gabriel-Pomona valleys. That boosted its client base from 16,000 to around 25,000, and NLS opened an office in El Monte. "
    Question0: "What is the language goal of neighborhood legal services?"Choices: A. Expand the Asian languages offered B. To offer more Spanish options C. To serve 39% of the population D. Have English and major Chinese languages become interchangeable E. To understand Asian culture F. Our goal is to have that for the major Asian languages as well.- to be interchangeable with English G. To serve 15% of the population H. To add French and German
Response: Answer0: ADF
'''

boolq = '''
1. Ant-Man and the Wasp is an upcoming American superhero film based on the Marvel Comics characters Scott Lang / Ant-Man and Hope van Dyne / Wasp. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is intended to be the sequel to 2015's Ant-Man, and the twentieth film in the Marvel Cinematic Universe (MCU). The film is directed by Peyton Reed and written by the writing teams of Chris McKenna and Erik Sommers, and Paul Rudd, Andrew Barrer and Gabriel Ferrari. It stars Rudd as Lang and Evangeline Lilly as Van Dyne, alongside Michael Peña, Walton Goggins, Bobby Cannavale, Judy Greer, Tip ``T.I.'' Harris, David Dastmalchian, Hannah John-Kamen, Abby Ryder Fortson, Randall Park, Michelle Pfeiffer, Laurence Fishburne, and Michael Douglas. In Ant-Man and the Wasp, the titular pair team up to embark on a new mission from Hank Pym. Question: is there going to be an ant man 2 movie. Answer is True
2. Kentucky generally has a 70 mph speed limit on rural freeways as of 2007. The speed limit is reduced to 55 on multi-lane highways in some urban areas (I-71/75 south of Cincinnati, I-64, I-65, I-71 and I-264 in Louisville, U.S. 60 bypass in Owensboro), and KY 4 in Lexington. There are two 50 mph areas in Louisville. One approaching the Sherman Minton Bridge crossing the Ohio River into Indiana on I-64, and one approaching the Kennedy Bridge on I-65 towards Indiana. The Transportation Cabinet is now authorized to raise any multilane, divided rural highway up to 65 MPH based on speed and design studies. Anyone may request an increase by contacting their local Transportation Cabinet office and specifying the roadway to be raised. Two-lane, undivided highways are limited to 55 MPH. Points are not assessed for speeds less than 10 mph over the speed limit only on limited access highways, or for tickets received by Kentucky licensed drivers out of state. Question: is there a speed limit on the ohio river. Answer is True
3. Marvel's Agents of S.H.I.E.L.D., or simply Agents of S.H.I.E.L.D., is an American television series created for ABC by Joss Whedon, Jed Whedon, and Maurissa Tancharoen, based on the Marvel Comics organization S.H.I.E.L.D. (Strategic Homeland Intervention, Enforcement, and Logistics Division), a fictional peacekeeping and spy agency in a world of superheroes. It is set in the Marvel Cinematic Universe (MCU), sharing continuity with the films and other television series of the franchise. The series is produced by ABC Studios, Marvel Television, and Mutant Enemy Productions, with Jed Whedon, Tancharoen, and Jeffrey Bell serving as showrunners. Question: is marvel agents of shield in the mcu. Answer is True
'''

boolq_distilled = '''
1. Ant-Man and the Wasp - upcoming American superhero film based on Marvel Comics characters Scott Lang / Ant-Man and Hope van Dyne / Wasp. Is there going to be an Ant-Man 2 movie? Answer is True
2. Kentucky - 70 mph speed limit on rural freeways as of 2007. Is there a speed limit on the Ohio River? Answer is True
3. Marvel's Agents of S.H.I.E.L.D. - American television series created for ABC by Joss Whedon, Jed Whedon, and Maurissa Tancharoen, based on Marvel Comics organization S.H.I.E.L.D. Is Marvel Agents of Shield in the MCU? Answer is True
'''

rc_1_distilled = '''
User: Passage: "Neighborhood Legal Services expands into areas with large Asian populations, addressing language and cultural barriers. They offer free legal services to those earning under $1,380 per month, including consumer, health, family, immigration, housing, public benefits, and labor legal services."
    Question0: "What is the language goal of neighborhood legal services?"
Response: Answer0: A. Expand the Asian languages offered. D. Have English and major Chinese languages become interchangeable. F. Our goal is to have that for the major Asian languages as well.
'''

rc_2 = '''
User: Passage: "The CIA's senior management saw problems with the armed Predator as well, problems that Clarke and even Black and Allen were inclined to minimize. One (which also applied to reconnaissance flights) was money. A Predator cost about $3 million. If the CIA flew Predators for its own reconnaissance or covert action purposes, it might be able to borrow them from the Air Force, but it was not clear that the Air Force would bear the cost if a vehicle went down. Deputy Secretary of Defense Wolfowitz took the position that the CIA should have to pay for it; the CIA disagreed. Second, Tenet in particular questioned whether he, as Director of Central Intelligence, should operate an armed Predator." This was new ground,"he told us. Tenet ticked off key questions: What is the chain of command? Who takes the shot? Are America's leaders comfortable with the CIA doing this, going outside of normal military command and control? Charlie Allen told us that when these questions were discussed at the CIA, he and the Agency's executive director, A. B." Buzzy" Krongard, had said that either one of them would be happy to pull the trigger, but Tenet was appalled, telling them that they had no authority to do it, nor did he. Third, the Hellfire warhead carried by the Predator needed work. It had been built to hit tanks, not people. It needed to be designed to explode in a different way, and even then had to be targeted with extreme precision. In the configuration planned by the Air Force through mid-2001, the Predator's missile would not be able to hit a moving vehicle. White House officials had seen the Predator video of the "man in white." On July 11, Hadley tried to hurry along preparation of the armed system. He directed McLaughlin, Wolfowitz, and Joint Chiefs Vice Chairman Richard Myers to deploy Predators capable of being armed no later than September 1. "
    Question0: "What kind of time frame did Hadley set for the preparation of the armed missile?"Choices: A. It needed to be desinged to explode on target B. On July 2011 he directed McLaughlin, Wolfowitz, and Joint Chiefs Vice Chairman Richard Myers to deploy Predators capable of being armed no later than September 1 C. It needed to be designed to explode in a different way, and even then had to be targeted with extreme precision D. Preparation
Response: Answer0: BC
'''

rc_3 = '''
User: Passage: Patricia Cross and her boyfriend Larry Osborne , two students in a San Francisco school , become expelled for the publication of an off-campus underground paper .  As a result , a philosophy professor , Dr. Jonathon Barnett , resigns his teaching position and decides to become an advocate for the counterculture youth movement and , specifically , the use of LSD .  The hippies of the Haight-Ashbury district first see him as a hero and then as something even more .  Dr. Barnett even makes an appearance on the Joe Pyne TV show to voice his support of the hippie community and the use of LSD .  One scheming young man sees the opportunity to build Dr. Barnett as the head of a cult centered around the use of LSD .  He hopes to earn profit from the users , Dr. Barnett's speeches known as `` happenings , '' and their lifestyles .  At a massive LSD-fueled dance , Patricia begins to have a bad trip Which leads to an argument between her and Pat , ultimately splitting the couple up .  After Patricia realizes that she's pregnant , Dr. Barnett advises her to have an abortion , ultimately leading to Patricia attempting suicide .  However , Larry saves her and makes the destruction of Dr. Barnett's cult his primary objective .  Larry shoots Dr. Barnett from the crowd at one of his massive speeches .  As another hippie in attendance calms the audience and Elliot sees his new leader for their cult-like organization , Larry realizes that his assassination of Dr. Barnett simply made him a martyr for the hippie movement . Question: Why was Dr. Barnett seen as the head of a cult centered around the use of LSD? Student's Answer: The hippies of the Haight-Ashbury district first see him as a hero and also his appearance on the Joe Pyne TV show to voice his support of the hippie community and the use of LSD.
Response: The student's answer is correct.

User: Passage: Once upon a time there was a princess who lived in a high tower and she was not allowed to leave because of her mean mother. One day she chose to leave but her mother would not let her. The princess climbed out the window of the high tower and climbed down the south wall when her mother was sleeping. She wandered out a good ways. Finally she went into the forest where there are no electric poles but where there are some caves. There she met a young man who was running. His name was John. John asked the princess why such a beautiful woman like her was out in the middle of a forest. She said that she had been trapped for her whole life by an evil woman who said she was her mother. The man said that he would take the princess to a castle that was near. He also said that he thought that she may be the missing princess. As they go through the forest they run into many problems. They see that they are lost and have no way of finding where to go. After several days pass, the princess climbs up to the top of a tree in order to find out where they are. She sees that the castle where they want to go is not that far away and near a mountain. After thinking of the best way to get there, John and the princess go to the castle where they live for the rest of their lives. Question: Who are the two main characters in the story? Student's Answer: The princess, the King and the Queen.
Response: The student's answer is wrong.
'''

rc_3_distilled = '''
User: Passage: Patricia Cross and her boyfriend Larry Osborne get expelled for publishing an off-campus underground paper. Dr. Jonathon Barnett resigns as a philosophy professor to support the counterculture youth movement and LSD. He becomes a cult figure. Larry tries to stop the cult. Question: Why was Dr. Barnett seen as the head of an LSD-centered cult? Student's Answer: The hippies saw him as a hero and due to his TV appearance supporting LSD.
Response: The student's answer is correct.

User: Passage: A princess escapes from her tower, meets John in a forest, and they go to a nearby castle. Question: Who are the two main characters? Student's Answer: The princess, the King, and the Queen.
Response: The student's answer is wrong.
'''
prompt_list = [
    # rc_1,
    # boolq,
    # boolq_distilled,
    # rc_1_distilled,
    # rc_2,
    rc_3,
    rc_3_distilled
]

for prompt in prompt_list:        
    prompt_tokens = tokenizer(prompt, return_tensors="pt").input_ids
    print(prompt_tokens.shape)